/* 
 * ***** FUNCTION *****
 * ARTWORKS VIEWS
 * Increment the views of an artwork 
 */

CREATE OR REPLACE FUNCTION GALLERY.INCREMENT_ARTWORK_VIEWS
(ARTWORK_ID BIGINT) RETURNS INT AS $$ 
	DECLARE VIEWS_COUNT INT;
	BEGIN
	UPDATE gallery.artworks
	SET views = views + 1
	WHERE id = artwork_id
	RETURNING
	    views INTO VIEWS_COUNT;
	RETURN VIEWS_COUNT;
	END;
	$$ LANGUAGE 
PLPGSQL; 

SELECT GALLERY.INCREMENT_ARTWORK_VIEWS(1);